export const CART_ACTIONS_TYPES = {
  SET_CART_ITEMS: "cart/SET_CART_ITEMS",
  TOGGLE_IS_CART_OPEN: "cart/TOGGLE_IS_CART_OPEN",
  SET_CART_COUNT: "cart/SET_CART_COUNT",
  SET_CART_TOTAL_PRICE: "cart/SET_CART_TOTAL_PRICE",
};
